/**
 * TravelEase Data Store
 * Comprehensive Database of 40 Indian Destinations, Budgets, Packages, Hotels, Flights & Gallery Data.
 * ALL PRICES IN INDIAN RUPEES (₹ / INR).
 */

const INITIAL_DESTINATIONS = [
  {
    id: "goa",
    name: "Goa",
    cityState: "Goa, India",
    region: "West India",
    travelType: "Beach",
    shortDesc: "Sun-kissed beaches, vibrant nightlife, Portuguese heritage, and watersports heaven.",
    bestTime: "Nov – Feb",
    numDays: "4 Days / 3 Nights",
    budgetStarting: 8000,
    avgDailyBudget: 2500,
    rating: 4.8,
    attractions: ["Baga Beach", "Calangute Beach", "Anjuna", "Vagator", "Palolem", "Fort Aguada", "Old Goa"],
    activities: ["Water Sports", "Beach Parties", "Cruising", "Heritage Walks", "Seafood Tasting"],
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "mumbai",
    name: "Mumbai",
    cityState: "Maharashtra",
    region: "West India",
    travelType: "Budget",
    shortDesc: "The City of Dreams with iconic colonial architecture, bustling street food, and Marine Drive views.",
    bestTime: "Oct – Mar",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 7500,
    avgDailyBudget: 2800,
    rating: 4.7,
    attractions: ["Gateway of India", "Marine Drive", "Elephanta Caves", "Colaba Causeway", "Chhatrapati Shivaji Terminus"],
    activities: ["Street Food Crawl", "Bollywood Tour", "Ferry Ride", "Heritage Walk"],
    image: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "pune",
    name: "Pune",
    cityState: "Maharashtra",
    region: "West India",
    travelType: "Heritage",
    shortDesc: "Cultural capital of Maharashtra known for Maratha empire forts, pleasant climate, and vibrant food culture.",
    bestTime: "Jul – Feb",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 5000,
    avgDailyBudget: 1800,
    rating: 4.5,
    attractions: ["Shaniwar Wada", "Aga Khan Palace", "Sinhagad Fort", "Dagdusheth Halwai Temple", "Osho Ashram"],
    activities: ["Fort Trekking", "Misal Pav Tasting", "Museum Tours", "Weekend Getaways"],
    image: "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "delhi",
    name: "Delhi",
    cityState: "Delhi NCR",
    region: "North India",
    travelType: "Heritage",
    shortDesc: "India's capital blending ancient Mughal monuments, vibrant markets, and modern metropolis life.",
    bestTime: "Oct – Mar",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 6500,
    avgDailyBudget: 2200,
    rating: 4.6,
    attractions: ["India Gate", "Red Fort", "Qutub Minar", "Humayun's Tomb", "Lotus Temple", "Chandni Chowk"],
    activities: ["Heritage Walks", "Chandni Chowk Food Tour", "Shopping at Dilli Haat", "Museum Visits"],
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "agra",
    name: "Agra",
    cityState: "Uttar Pradesh",
    region: "North India",
    travelType: "Heritage",
    shortDesc: "Home to the world's most breathtaking symbol of love, the Taj Mahal, and majestic Mughal forts.",
    bestTime: "Oct – Mar",
    numDays: "2 Days / 1 Night",
    budgetStarting: 4500,
    avgDailyBudget: 2000,
    rating: 4.9,
    attractions: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh", "Itimad-ud-Daulah"],
    activities: ["Sunrise Taj Visit", "Petha Tasting", "Mughal Architecture Tour", "Yamuna Sunset View"],
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "jaipur",
    name: "Jaipur",
    cityState: "Rajasthan",
    region: "North India",
    travelType: "Heritage",
    shortDesc: "The Pink City featuring grand palaces, royal hill forts, vibrant bazaars, and rich Marwari heritage.",
    bestTime: "Nov – Mar",
    numDays: "4 Days / 3 Nights",
    budgetStarting: 8500,
    avgDailyBudget: 2400,
    rating: 4.8,
    attractions: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar", "Nahargarh Fort", "Chokhi Dhani"],
    activities: ["Hot Air Ballooning", "Elephant Safari", "Hand Block Printing", "Royal Dining"],
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "udaipur",
    name: "Udaipur",
    cityState: "Rajasthan",
    region: "North India",
    travelType: "Honeymoon",
    shortDesc: "The City of Lakes with romantic marble palaces floating on serene blue waters and regal hospitality.",
    bestTime: "Sep – Mar",
    numDays: "4 Days / 3 Nights",
    budgetStarting: 9500,
    avgDailyBudget: 2800,
    rating: 4.9,
    attractions: ["City Palace", "Lake Pichola", "Jag Mandir", "Fateh Sagar Lake", "Saheliyon Ki Bari"],
    activities: ["Sunset Boat Ride", "Rooftop Dining", "Puppet Shows", "Palace Tour"],
    image: "https://images.unsplash.com/photo-1615836245337-f5b9b2303f1c?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "jodhpur",
    name: "Jodhpur",
    cityState: "Rajasthan",
    region: "North India",
    travelType: "Heritage",
    shortDesc: "The Blue City dominated by the towering Mehrangarh Fort and indigo-painted old town streets.",
    bestTime: "Oct – Mar",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 7000,
    avgDailyBudget: 2200,
    rating: 4.7,
    attractions: ["Mehrangarh Fort", "Jaswant Thada", "Umaid Bhawan Palace", "Toorji Ka Jhalra"],
    activities: ["Zip-lining at Fort", "Blue City Walking Tour", "Bishnoi Village Safari"],
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "jaisalmer",
    name: "Jaisalmer",
    cityState: "Rajasthan",
    region: "North India",
    travelType: "Adventure",
    shortDesc: "The Golden City located in the heart of the Thar Desert, renowned for sand dunes and golden fort.",
    bestTime: "Oct – Mar",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 8500,
    avgDailyBudget: 2600,
    rating: 4.8,
    attractions: ["Jaisalmer Fort", "Sam Sand Dunes", "Patwon Ki Haveli", "Gadisar Lake"],
    activities: ["Desert Camping", "Camel Safari", "Dune Bashing", "Folk Dance Nights"],
    image: "https://images.unsplash.com/photo-1572445271230-a78b5944a659?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "varanasi",
    name: "Varanasi",
    cityState: "Uttar Pradesh",
    region: "North India",
    travelType: "Spiritual",
    shortDesc: "The spiritual heart of India along the sacred Ganges River, famous for ancient ghats and Ganga Aarti.",
    bestTime: "Oct – Mar",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 5000,
    avgDailyBudget: 1800,
    rating: 4.8,
    attractions: ["Dashashwamedh Ghat", "Kashi Vishwanath Temple", "Sarnath", "Manikarnika Ghat", "Assi Ghat"],
    activities: ["Ganga Aarti Ceremony", "Sunrise Boat Ride", "Silk Saree Shopping", "Sarnath Stupa Tour"],
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "rishikesh",
    name: "Rishikesh",
    cityState: "Uttarakhand",
    region: "North India",
    travelType: "Adventure",
    shortDesc: "Yoga Capital of the World nestled in the Himalayan foothills along the crystal-clear Ganges.",
    bestTime: "Sep – Jun",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 5000,
    avgDailyBudget: 1700,
    rating: 4.8,
    attractions: ["Laxman Jhula", "Ram Jhula", "Beatles Ashram", "Triveni Ghat", "Shivpuri"],
    activities: ["White Water Rafting", "Bungee Jumping", "Yoga & Meditation", "Riverside Camping"],
    image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "manali",
    name: "Manali",
    cityState: "Himachal Pradesh",
    region: "North India",
    travelType: "Mountains",
    shortDesc: "Himalayan resort town famous for snow-capped peaks, pine forests, valley adventures, and Solang snow.",
    bestTime: "Oct – Jun",
    numDays: "5 Days / 4 Nights",
    budgetStarting: 8000,
    avgDailyBudget: 2200,
    rating: 4.8,
    attractions: ["Solang Valley", "Hidimba Temple", "Old Manali", "Rohtang Pass", "Mall Road", "Jogini Waterfalls"],
    activities: ["Paragliding", "Skiing & Snowboarding", "Trekking", "Cafe Hopping in Old Manali"],
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "shimla",
    name: "Shimla",
    cityState: "Himachal Pradesh",
    region: "North India",
    travelType: "Mountains",
    shortDesc: "The Queen of Hills featuring colonial Mall Road, Kalka-Shimla toy train, and scenic valley vistas.",
    bestTime: "Mar – Jun, Dec – Jan",
    numDays: "4 Days / 3 Nights",
    budgetStarting: 7500,
    avgDailyBudget: 2100,
    rating: 4.6,
    attractions: ["The Ridge", "Mall Road", "Jakhoo Temple", "Kufri", "Christ Church"],
    activities: ["Toy Train Ride", "Ice Skating", "Nature Walks", "Kufri Adventure Park"],
    image: "https://images.unsplash.com/photo-1597074866923-dc0589150358?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "dharamshala",
    name: "Dharamshala",
    cityState: "Himachal Pradesh",
    region: "North India",
    travelType: "Spiritual",
    shortDesc: "Serene residence of His Holiness Dalai Lama in McLeod Ganj surrounded by Dhauladhar ranges.",
    bestTime: "Sep – Jun",
    numDays: "4 Days / 3 Nights",
    budgetStarting: 7000,
    avgDailyBudget: 1900,
    rating: 4.7,
    attractions: ["McLeod Ganj", "Namgyal Monastery", "Triund Hill", "Bhagsunag Waterfall", "HPCA Stadium"],
    activities: ["Triund Trek", "Tibetan Meditation", "Monastery Visits", "Cafe Hopping"],
    image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "srinagar",
    name: "Srinagar",
    cityState: "Jammu & Kashmir",
    region: "North India",
    travelType: "Honeymoon",
    shortDesc: "Paradise on Earth with iconic Shikara rides on Dal Lake, floating gardens, and Mughal terraced gardens.",
    bestTime: "Apr – Oct",
    numDays: "5 Days / 4 Nights",
    budgetStarting: 12000,
    avgDailyBudget: 3200,
    rating: 4.9,
    attractions: ["Dal Lake", "Shalimar Bagh", "Nishat Bagh", "Shankaracharya Temple", "Pari Mahal"],
    activities: ["Houseboat Stay", "Shikara Ride", "Tulip Garden Visit", "Shopping Pashmina Shawls"],
    image: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "leh-ladakh",
    name: "Leh-Ladakh",
    cityState: "Ladakh",
    region: "North India",
    travelType: "Adventure",
    shortDesc: "Land of High Passes featuring surreal moonscapes, turquoise Pangong Lake, and ancient monasteries.",
    bestTime: "May – Sep",
    numDays: "7 Days / 6 Nights",
    budgetStarting: 20000,
    avgDailyBudget: 4200,
    rating: 4.9,
    attractions: ["Leh Palace", "Nubra Valley", "Pangong Lake", "Khardung La Pass", "Shanti Stupa", "Magnetic Hill"],
    activities: ["High Altitude Biking", "Double Humped Camel Ride", "Stargazing at Pangong", "Monastery Touring"],
    image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "amritsar",
    name: "Amritsar",
    cityState: "Punjab",
    region: "North India",
    travelType: "Spiritual",
    shortDesc: "Spiritual sanctuary of the Sikhs home to the shimmering Golden Temple and legendary Punjabi hospitality.",
    bestTime: "Oct – Mar",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 5500,
    avgDailyBudget: 1900,
    rating: 4.9,
    attractions: ["Golden Temple", "Wagah Border", "Jallianwala Bagh", "Partition Museum", "Gobindgarh Fort"],
    activities: ["Langar Experience", "Wagah Border Parade", "Amritsari Kulcha Tasting", "Heritage Walk"],
    image: "https://images.unsplash.com/photo-1514222709107-a180c68d72b4?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "kolkata",
    name: "Kolkata",
    cityState: "West Bengal",
    region: "East India",
    travelType: "Heritage",
    shortDesc: "City of Joy renowned for colonial heritage, grand Victoria Memorial, yellow taxis, and artistic culture.",
    bestTime: "Oct – Mar",
    numDays: "4 Days / 3 Nights",
    budgetStarting: 6500,
    avgDailyBudget: 2000,
    rating: 4.6,
    attractions: ["Victoria Memorial", "Howrah Bridge", "Dakshineswar Kali Temple", "Park Street", "Indian Museum"],
    activities: ["Tram Ride", "Sweet Tasting (Rosogolla)", "Hooghly River Ferry", "Book Market Walk"],
    image: "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "darjeeling",
    name: "Darjeeling",
    cityState: "West Bengal",
    region: "East India",
    travelType: "Mountains",
    shortDesc: "Queen of the Hills offering views of Kanchenjunga, world-famous tea gardens, and Himalayan Railway.",
    bestTime: "Oct – May",
    numDays: "4 Days / 3 Nights",
    budgetStarting: 8500,
    avgDailyBudget: 2300,
    rating: 4.7,
    attractions: ["Tiger Hill", "Batasia Loop", "Happy Valley Tea Estate", "Himalayan Mountaineering Institute"],
    activities: ["Sunrise over Kanchenjunga", "UNESCO Toy Train Ride", "Tea Tasting Session"],
    image: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "sikkim",
    name: "Sikkim",
    cityState: "Sikkim",
    region: "East India",
    travelType: "Mountains",
    shortDesc: "Eco-paradise of Gangtok, glacial Tsomgo Lake, Nathula Pass, and vibrant Buddhist monasteries.",
    bestTime: "Mar – May, Oct – Dec",
    numDays: "5 Days / 4 Nights",
    budgetStarting: 11000,
    avgDailyBudget: 2700,
    rating: 4.8,
    attractions: ["Gangtok MG Marg", "Tsomgo Lake", "Nathula Pass", "Rumtek Monastery", "Yumthang Valley"],
    activities: ["Cable Car Ride", "Yak Safari at Tsomgo", "Monastery Trails", "Organic Food Tasting"],
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "kerala",
    name: "Kerala",
    cityState: "Kerala",
    region: "South India",
    travelType: "Honeymoon",
    shortDesc: "God's Own Country offering serene backwaters, tea plantation mist, spice gardens, and Ayurvedic spa.",
    bestTime: "Sep – Mar",
    numDays: "5 Days / 4 Nights",
    budgetStarting: 12000,
    avgDailyBudget: 3000,
    rating: 4.9,
    attractions: ["Kochi Fort", "Munnar Tea Hills", "Alleppey Backwaters", "Thekkady Periyar", "Kovalam Beach"],
    activities: ["Houseboat Cruise", "Ayurvedic Massage", "Kathakali Performance", "Spice Plantation Tour"],
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "munnar",
    name: "Munnar",
    cityState: "Kerala",
    region: "South India",
    travelType: "Mountains",
    shortDesc: "Hill station wrapped in rolling emerald tea gardens, misty valleys, and endangered Nilgiri Tahr.",
    bestTime: "Sep – May",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 7500,
    avgDailyBudget: 2200,
    rating: 4.8,
    attractions: ["Eravikulam National Park", "Mattupetty Dam", "Tea Museum", "Anamudi Peak", "Top Station"],
    activities: ["Tea Tasting", "Trekking", "Wildlife Spotting", "Waterfall Visits"],
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "alleppey",
    name: "Alleppey",
    cityState: "Kerala",
    region: "South India",
    travelType: "Honeymoon",
    shortDesc: "Venice of the East world-renowned for traditional luxury houseboat stays along quiet coconut palm canals.",
    bestTime: "Nov – Feb",
    numDays: "2 Days / 1 Night",
    budgetStarting: 6000,
    avgDailyBudget: 2800,
    rating: 4.9,
    attractions: ["Alleppey Backwaters", "Marari Beach", "Vembanad Lake", "Alappuzha Lighthouse"],
    activities: ["Overnight Houseboat Stay", "Kayaking Canals", "Sunset Beach Walks"],
    image: "https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "kochi",
    name: "Kochi",
    cityState: "Kerala",
    region: "South India",
    travelType: "Heritage",
    shortDesc: "Coastal port city blending Portuguese, Dutch, Chinese, and Jewish heritage with modern arts.",
    bestTime: "Oct – Mar",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 6500,
    avgDailyBudget: 2100,
    rating: 4.7,
    attractions: ["Fort Kochi", "Chinese Fishing Nets", "Mattancherry Palace", "Jew Town", "Marine Drive Kochi"],
    activities: ["Heritage Walking Tour", "Kochi-Muziris Biennale", "Seafood Dining"],
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "ooty",
    name: "Ooty",
    cityState: "Tamil Nadu",
    region: "South India",
    travelType: "Mountains",
    shortDesc: "Queen of Nilgiris with aromatic eucalyptus groves, botanical gardens, and Nilgiri Mountain Railway.",
    bestTime: "Oct – Jun",
    numDays: "4 Days / 3 Nights",
    budgetStarting: 7500,
    avgDailyBudget: 2100,
    rating: 4.7,
    attractions: ["Ooty Lake", "Doddabetta Peak", "Government Botanical Garden", "Rose Garden", "Pykara Falls"],
    activities: ["Nilgiri Toy Train Ride", "Boating at Ooty Lake", "Homemade Chocolate Shopping"],
    image: "https://images.unsplash.com/photo-1589136777351-fdc9c9ca003b?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "coorg",
    name: "Coorg",
    cityState: "Karnataka",
    region: "South India",
    travelType: "Mountains",
    shortDesc: "Scotland of India famed for lush coffee plantations, spice estates, cascading waterfalls, and Kodava culture.",
    bestTime: "Oct – Apr",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 7000,
    avgDailyBudget: 2200,
    rating: 4.8,
    attractions: ["Abbey Falls", "Raja's Seat", "Namdroling Monastery (Golden Temple)", "Dubare Elephant Camp"],
    activities: ["Coffee Plantation Tour", "Elephant Interaction", "Trekking to Tadiandamol"],
    image: "https://images.unsplash.com/photo-1600100395162-43210e7ee339?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "bengaluru",
    name: "Bengaluru",
    cityState: "Karnataka",
    region: "South India",
    travelType: "Budget",
    shortDesc: "Silicon Valley of India with pleasant climate, verdant gardens, craft breweries, and royal palaces.",
    bestTime: "Sep – Feb",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 6000,
    avgDailyBudget: 2200,
    rating: 4.5,
    attractions: ["Bengaluru Palace", "Lalbagh Botanical Garden", "Cubbon Park", "ISKCON Temple", "UB City"],
    activities: ["Microbrewery Hopping", "Palace Tour", "Street Shopping at Commercial Street"],
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "hyderabad",
    name: "Hyderabad",
    cityState: "Telangana",
    region: "South India",
    travelType: "Heritage",
    shortDesc: "City of Pearls famous for Nizam heritage, iconic Charminar, world's largest Ramoji Film City, and Biryani.",
    bestTime: "Oct – Mar",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 6500,
    avgDailyBudget: 2100,
    rating: 4.7,
    attractions: ["Charminar", "Golconda Fort", "Ramoji Film City", "Hussain Sagar Lake", "Chowmahalla Palace"],
    activities: ["Hyderabadi Biryani Feast", "Pearl Shopping", "Sound & Light Show at Golconda"],
    image: "https://images.unsplash.com/photo-1605379399642-870262d3d051?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "chennai",
    name: "Chennai",
    cityState: "Tamil Nadu",
    region: "South India",
    travelType: "Beach",
    shortDesc: "Gateway to South India boasting Asia's longest urban beach, Dravidian temples, and Carnatic music.",
    bestTime: "Nov – Feb",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 6000,
    avgDailyBudget: 2000,
    rating: 4.5,
    attractions: ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George", "Santhome Cathedral", "Mahabalipuram Nearby"],
    activities: ["Sunrise at Marina Beach", "Filter Coffee Tasting", "Dravidian Architecture Tour"],
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "andaman",
    name: "Andaman & Nicobar",
    cityState: "Andaman & Nicobar Islands",
    region: "Islands",
    travelType: "Beach",
    shortDesc: "Tropical paradise with white-sand Radhanagar Beach, crystal-clear turquoise waters, and scuba diving.",
    bestTime: "Oct – May",
    numDays: "5 Days / 4 Nights",
    budgetStarting: 15000,
    avgDailyBudget: 3800,
    rating: 4.9,
    attractions: ["Port Blair Cellular Jail", "Havelock Island (Swaraj Dweep)", "Radhanagar Beach", "Neil Island"],
    activities: ["Scuba Diving", "Snorkeling", "Glass Bottom Boat Ride", "Light & Sound Show at Cellular Jail"],
    image: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    cityState: "Meghalaya",
    region: "Northeast India",
    travelType: "Adventure",
    shortDesc: "Abode of Clouds featuring double-decker Living Root Bridges, crystal clear Dawki River, and waterfalls.",
    bestTime: "Oct – Apr",
    numDays: "5 Days / 4 Nights",
    budgetStarting: 10000,
    avgDailyBudget: 2400,
    rating: 4.9,
    attractions: ["Shillong", "Cherrapunji (Sohra)", "Dawki River", "Living Root Bridges", "Nohkalikai Falls"],
    activities: ["Trekking Living Root Bridges", "Boating in Crystal Dawki", "Cave Exploration"],
    image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "ranthambore",
    name: "Ranthambore",
    cityState: "Rajasthan",
    region: "North India",
    travelType: "Wildlife",
    shortDesc: "Premier tiger reserve where majestic Royal Bengal Tigers roam freely around ancient hill fort ruins.",
    bestTime: "Oct – Jun",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 8000,
    avgDailyBudget: 2700,
    rating: 4.8,
    attractions: ["Ranthambore National Park", "Ranthambore Fort", "Padam Talao", "Trinetra Ganesh Temple"],
    activities: ["Jungle Jeep Safari", "Canter Safari", "Bird Watching", "Fort Trek"],
    image: "https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "mathura",
    name: "Mathura",
    cityState: "Uttar Pradesh",
    region: "North India",
    travelType: "Spiritual",
    shortDesc: "Sacred birthplace of Lord Krishna along the Yamuna River, famous for Janmashtami and vibrant Holi celebrations.",
    bestTime: "Oct – Mar",
    numDays: "2 Days / 1 Night",
    budgetStarting: 4000,
    avgDailyBudget: 1500,
    rating: 4.7,
    attractions: ["Shri Krishna Janmabhoomi", "Dwarkadhish Temple", "Vishram Ghat", "Govardhan Hill"],
    activities: ["Yamuna Aarti", "Peda Tasting", "Temple Parikrama", "Cultural Festivities"],
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "haridwar",
    name: "Haridwar",
    cityState: "Uttarakhand",
    region: "North India",
    travelType: "Spiritual",
    shortDesc: "Gateway to the Gods where the holy Ganga enters the Indo-Gangetic plains, famed for Har Ki Pauri Ganga Aarti.",
    bestTime: "Sep – Apr",
    numDays: "2 Days / 1 Night",
    budgetStarting: 4500,
    avgDailyBudget: 1600,
    rating: 4.8,
    attractions: ["Har Ki Pauri", "Mansa Devi Temple", "Chandi Devi Temple", "Kankhal", "Shanti Kunj"],
    activities: ["Grand Evening Ganga Aarti", "Cable Car to Mansa Devi", "Holy Dip in Ganga"],
    image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "ayodhya",
    name: "Ayodhya",
    cityState: "Uttar Pradesh",
    region: "North India",
    travelType: "Spiritual",
    shortDesc: "Ancient holy city on the banks of Saryu River, birthplace of Lord Rama home to the majestic Shri Ram Janmabhoomi Mandir.",
    bestTime: "Oct – Mar",
    numDays: "2 Days / 1 Night",
    budgetStarting: 4500,
    avgDailyBudget: 1600,
    rating: 4.9,
    attractions: ["Shri Ram Janmabhoomi Temple", "Hanuman Garhi", "Kanak Bhawan", "Saryu Ghats", "Treta Ke Thakur"],
    activities: ["Saryu River Aarti", "Temple Pilgrimage", "Deepotsav Experience", "Heritage Walk"],
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "mysore",
    name: "Mysore",
    cityState: "Karnataka",
    region: "South India",
    travelType: "Heritage",
    shortDesc: "City of Palaces known for illuminated Mysore Palace, Chamundi Hills, silk sarees, and Royal Dasara.",
    bestTime: "Oct – Mar",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 6000,
    avgDailyBudget: 1900,
    rating: 4.7,
    attractions: ["Mysore Palace", "Chamundeshwari Temple", "Brindavan Gardens", "St. Philomena's Church", "Mysore Zoo"],
    activities: ["Palace Illumination Viewing", "Mysore Pak Tasting", "Silk Saree Shopping"],
    image: "https://images.unsplash.com/photo-1600100395162-43210e7ee339?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "hampi",
    name: "Hampi",
    cityState: "Karnataka",
    region: "South India",
    travelType: "Heritage",
    shortDesc: "UNESCO World Heritage site featuring stone chariot, boulder-strewn landscapes, and ruins of Vijayanagara Empire.",
    bestTime: "Oct – Feb",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 5500,
    avgDailyBudget: 1800,
    rating: 4.9,
    attractions: ["Virupaksha Temple", "Vittala Temple Stone Chariot", "Lotus Mahal", "Elephant Stables", "Matanga Hill"],
    activities: ["Coracle Ride on Tungabhadra", "Matanga Hill Sunrise Trek", "Bicycle Ruins Tour"],
    image: "https://images.unsplash.com/photo-1600100395162-43210e7ee339?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "rann-of-kutch",
    name: "Rann of Kutch",
    cityState: "Gujarat",
    region: "West India",
    travelType: "Adventure",
    shortDesc: "World's largest salt marsh turning into an ethereal white desert under full moon during Rann Utsav.",
    bestTime: "Nov – Feb",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 9000,
    avgDailyBudget: 2800,
    rating: 4.8,
    attractions: ["White Rann", "Kalo Dungar (Black Hill)", "Dhordo Tent City", "Mandvi Beach", "Aina Mahal"],
    activities: ["Full Moon White Desert Walk", "Rann Utsav Cultural Nights", "Handicraft Village Tour"],
    image: "https://images.unsplash.com/photo-1572445271230-a78b5944a659?auto=format&fit=crop&w=800&q=80",
    isPopular: true
  },
  {
    id: "mahabaleshwar",
    name: "Mahabaleshwar",
    cityState: "Maharashtra",
    region: "West India",
    travelType: "Mountains",
    shortDesc: "Western Ghats hill station famous for strawberry farms, panoramic lookouts, and Mapro Garden treats.",
    bestTime: "Oct – Jun",
    numDays: "3 Days / 2 Nights",
    budgetStarting: 6000,
    avgDailyBudget: 2000,
    rating: 4.6,
    attractions: ["Arthur's Seat", "Venna Lake", "Mapro Garden", "Pratapgad Fort", "Elephant's Head Point"],
    activities: ["Fresh Strawberry Plucking", "Venna Lake Boating", "Pratapgad Trek"],
    image: "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  },
  {
    id: "khajuraho",
    name: "Khajuraho",
    cityState: "Madhya Pradesh",
    region: "Central India",
    travelType: "Heritage",
    shortDesc: "UNESCO World Heritage site celebrated for intricate Nagara-style temples and delicate stone carvings.",
    bestTime: "Oct – Mar",
    numDays: "2 Days / 1 Night",
    budgetStarting: 5000,
    avgDailyBudget: 1800,
    rating: 4.7,
    attractions: ["Kandariya Mahadeva Temple", "Western Group of Temples", "Raneh Falls", "Light & Sound Show"],
    activities: ["Temple Architecture Walk", "Sound & Light Show", "Raneh Canyon Safari"],
    image: "https://images.unsplash.com/photo-1600100395162-43210e7ee339?auto=format&fit=crop&w=800&q=80",
    isPopular: false
  }
];

// DEMO BUDGET GUIDES FOR MAJOR INDIAN DESTINATIONS
const DEMO_REGIONAL_BUDGETS = [
  {
    destination: "Goa",
    duration: "4 Days / 3 Nights",
    budgetRange: "₹8,000 – ₹15,000 per person",
    midRange: "₹15,000 – ₹25,000",
    luxury: "₹30,000+",
    places: ["Baga Beach", "Calangute Beach", "Anjuna", "Vagator", "Palolem", "Fort Aguada", "Old Goa"]
  },
  {
    destination: "Rajasthan",
    duration: "6 Days / 5 Nights",
    budgetRange: "₹12,000 – ₹20,000 per person",
    midRange: "₹20,000 – ₹35,000",
    luxury: "₹40,000+",
    places: ["Jaipur", "Jodhpur", "Udaipur", "Jaisalmer", "Pushkar"]
  },
  {
    destination: "Kerala",
    duration: "5 Days / 4 Nights",
    budgetRange: "₹12,000 – ₹20,000 per person",
    midRange: "₹20,000 – ₹35,000",
    luxury: "₹40,000+",
    places: ["Kochi", "Munnar", "Alleppey", "Thekkady", "Kovalam"]
  },
  {
    destination: "Manali",
    duration: "5 Days / 4 Nights",
    budgetRange: "₹8,000 – ₹15,000 per person",
    midRange: "₹15,000 – ₹25,000",
    luxury: "₹30,000+",
    places: ["Solang Valley", "Hidimba Temple", "Old Manali", "Rohtang / Nearby Mountains", "Mall Road"]
  },
  {
    destination: "Kashmir",
    duration: "6 Days / 5 Nights",
    budgetRange: "₹15,000 – ₹25,000 per person",
    midRange: "₹25,000 – ₹40,000",
    luxury: "₹45,000+",
    places: ["Srinagar", "Dal Lake", "Gulmarg", "Pahalgam", "Sonamarg"]
  },
  {
    destination: "Ladakh",
    duration: "7 Days / 6 Nights",
    budgetRange: "₹20,000 – ₹35,000 per person",
    midRange: "₹35,000 – ₹50,000",
    luxury: "₹60,000+",
    places: ["Leh", "Nubra Valley", "Pangong Lake", "Khardung La", "Shanti Stupa"]
  },
  {
    destination: "Golden Triangle (Agra + Delhi + Jaipur)",
    duration: "6 Days / 5 Nights",
    budgetRange: "₹12,000 – ₹20,000 per person",
    midRange: "₹20,000 – ₹35,000",
    luxury: "₹40,000+",
    places: ["India Gate", "Red Fort", "Taj Mahal", "Agra Fort", "Amber Fort", "Hawa Mahal", "City Palace"]
  },
  {
    destination: "Varanasi",
    duration: "3 Days / 2 Nights",
    budgetRange: "₹5,000 – ₹10,000 per person",
    midRange: "₹10,000 – ₹18,000",
    luxury: "₹20,000+",
    places: ["Ganga Aarti", "Dashashwamedh Ghat", "Kashi Vishwanath Temple", "Sarnath", "Boat Ride"]
  },
  {
    destination: "Rishikesh",
    duration: "3 Days / 2 Nights",
    budgetRange: "₹5,000 – ₹10,000 per person",
    midRange: "₹10,000 – ₹18,000",
    luxury: "₹20,000+",
    places: ["River Rafting", "Laxman Jhula area", "Ganga Aarti", "Yoga", "Adventure activities"]
  },
  {
    destination: "Andaman",
    duration: "5 Days / 4 Nights",
    budgetRange: "₹15,000 – ₹25,000 per person",
    midRange: "₹25,000 – ₹40,000",
    luxury: "₹45,000+",
    places: ["Port Blair", "Havelock / Swaraj Dweep", "Radhanagar Beach", "Neil / Shaheed Dweep", "Water Sports"]
  },
  {
    destination: "Meghalaya",
    duration: "5 Days / 4 Nights",
    budgetRange: "₹10,000 – ₹18,000 per person",
    midRange: "₹18,000 – ₹30,000",
    luxury: "₹35,000+",
    places: ["Shillong", "Cherrapunji", "Dawki", "Living Root Bridges", "Waterfalls"]
  }
];

// SAMPLE TOUR PACKAGES IN INR
const INITIAL_PACKAGES = [
  {
    id: "pkg-goa",
    title: "Goa Beach Escape",
    duration: "4 Days / 3 Nights",
    pricePerPerson: 9999,
    destination: "Goa",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["3-Star Hotel Stay", "Daily Breakfast", "South Goa Tour", "Mandovi River Cruise"],
    rating: 4.8
  },
  {
    id: "pkg-rajasthan",
    title: "Royal Rajasthan",
    duration: "6 Days / 5 Nights",
    pricePerPerson: 18999,
    destination: "Jaipur, Jodhpur, Udaipur",
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["Heritage Hotel Stay", "AC Cab Transfer", "Fort & Palace Entry Passes", "Cultural Dinner"],
    rating: 4.9
  },
  {
    id: "pkg-kerala",
    title: "Kerala Backwater Experience",
    duration: "5 Days / 4 Nights",
    pricePerPerson: 16999,
    destination: "Munnar & Alleppey",
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["1 Night Luxury Houseboat", "Munnar Resort Stay", "Tea Garden Safari", "All Meals on Houseboat"],
    rating: 4.9
  },
  {
    id: "pkg-kashmir",
    title: "Kashmir Paradise",
    duration: "6 Days / 5 Nights",
    pricePerPerson: 21999,
    destination: "Srinagar, Gulmarg, Pahalgam",
    image: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["Dal Lake Houseboat Night", "Shikara Ride", "Gulmarg Gondola Ticket", "Airport Pickup/Drop"],
    rating: 4.9
  },
  {
    id: "pkg-manali",
    title: "Manali Adventure",
    duration: "5 Days / 4 Nights",
    pricePerPerson: 12999,
    destination: "Manali & Solang Valley",
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["Volvo Bus Roundtrip", "Valley View Resort", "Solang Snow Activity Pass", "Bonfire Evening"],
    rating: 4.8
  },
  {
    id: "pkg-golden-triangle",
    title: "Golden Triangle India",
    duration: "6 Days / 5 Nights",
    pricePerPerson: 17999,
    destination: "Delhi, Agra & Jaipur",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["Private Sedan Cab", "Sunrise Taj Mahal Entry", "Amber Fort Guide", "Hotel Breakfasts"],
    rating: 4.9
  },
  {
    id: "pkg-varanasi",
    title: "Varanasi Spiritual Journey",
    duration: "3 Days / 2 Nights",
    pricePerPerson: 7999,
    destination: "Varanasi & Sarnath",
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["Ghat Side Hotel", "VIP Ganga Aarti Pass", "Sunrise & Sunset Boat Tours", "Sarnath Excursion"],
    rating: 4.8
  },
  {
    id: "pkg-ladakh",
    title: "Ladakh Adventure",
    duration: "7 Days / 6 Nights",
    pricePerPerson: 29999,
    destination: "Leh, Nubra & Pangong",
    image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["Oxygen Cylinder in Vehicle", "Pangong Lake Luxury Camp", "Inner Line Permits", "All Meals"],
    rating: 4.9
  },
  {
    id: "pkg-andaman",
    title: "Andaman Island Escape",
    duration: "5 Days / 4 Nights",
    pricePerPerson: 24999,
    destination: "Port Blair & Havelock",
    image: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["Catamaran Cruise Transfers", "Beachside Resort Stay", "Complimentary Snorkeling", "Cellular Jail Pass"],
    rating: 4.9
  },
  {
    id: "pkg-meghalaya",
    title: "Meghalaya Explorer",
    duration: "5 Days / 4 Nights",
    pricePerPerson: 15999,
    destination: "Shillong, Cherrapunji & Dawki",
    image: "https://images.unsplash.com/photo-1506461883276-594a12b11cf3?auto=format&fit=crop&w=800&q=80",
    tag: "Starting from / Demo Package Price",
    inclusions: ["SUV Transport", "Living Root Bridge Guide", "Dawki Boating Pass", "Pine Hill Homestays"],
    rating: 4.8
  }
];

// SAMPLE HOTELS IN INR
const SAMPLE_HOTELS = [
  {
    id: "hotel-goa-1",
    name: "Goa Sun & Sands Resort",
    city: "Goa",
    tier: "3-Star",
    pricePerNight: 2499,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
    amenities: ["Swimming Pool", "Beachfront Access", "Free WiFi", "Breakfast Included"]
  },
  {
    id: "hotel-jaipur-1",
    name: "Jaipur Heritage Haveli",
    city: "Jaipur",
    tier: "Budget",
    pricePerNight: 1999,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
    amenities: ["Rooftop Restaurant", "Traditional Decor", "AC Rooms", "Free WiFi"]
  },
  {
    id: "hotel-manali-1",
    name: "Manali Alpine Pine Retreat",
    city: "Manali",
    tier: "3-Star",
    pricePerNight: 2299,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
    amenities: ["Mountain View Balcony", "Heater Available", "Bonfire Yard", "Restaurant"]
  },
  {
    id: "hotel-kerala-1",
    name: "Kerala Misty Hills & Backwaters Resort",
    city: "Kerala",
    tier: "4-Star",
    pricePerNight: 2799,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80",
    amenities: ["Ayurvedic Spa", "Infinity Pool", "Lake View", "Organic Dining"]
  },
  {
    id: "hotel-mumbai-1",
    name: "Marine Drive Premier Bay Hotel",
    city: "Mumbai",
    tier: "4-Star",
    pricePerNight: 3499,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80",
    amenities: ["Sea View Rooms", "Gym", "Concierge", "24/7 Room Service"]
  },
  {
    id: "hotel-delhi-1",
    name: "Delhi Connaught Plaza Hotel",
    city: "Delhi",
    tier: "3-Star",
    pricePerNight: 2499,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80",
    amenities: ["Metro Proximity", "Buffet Breakfast", "Airport Shuttle", "WiFi"]
  },
  {
    id: "hotel-kashmir-1",
    name: "Srinagar Royal Lake Palace",
    city: "Kashmir",
    tier: "4-Star",
    pricePerNight: 3499,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80",
    amenities: ["Dal Lake View", "Heated Rooms", "Shikara Pickup", "Traditional Kahwa Tea"]
  },
  {
    id: "hotel-udaipur-luxury",
    name: "Udaipur Lakefront Heritage Palace",
    city: "Udaipur",
    tier: "5-Star",
    pricePerNight: 12500,
    rating: 5.0,
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80",
    amenities: ["Royal Butler Service", "Private Boat Transfer", "Fine Dining", "Infinity Pool"]
  }
];

// SAMPLE DOMESTIC FLIGHTS IN INR
const SAMPLE_FLIGHTS = [
  { id: "fl-1", origin: "Mumbai", destination: "Goa", airline: "IndiGo", flightNo: "6E-241", startingPrice: 2499, duration: "1h 10m" },
  { id: "fl-2", origin: "Delhi", destination: "Mumbai", airline: "Air India", flightNo: "AI-805", startingPrice: 4499, duration: "2h 15m" },
  { id: "fl-3", origin: "Mumbai", destination: "Delhi", airline: "Vistara", flightNo: "UK-944", startingPrice: 4499, duration: "2h 10m" },
  { id: "fl-4", origin: "Delhi", destination: "Jaipur", airline: "Alliance Air", flightNo: "9I-643", startingPrice: 2999, duration: "0h 55m" },
  { id: "fl-5", origin: "Mumbai", destination: "Kochi", airline: "Akasa Air", flightNo: "QP-1122", startingPrice: 4999, duration: "1h 55m" },
  { id: "fl-6", origin: "Delhi", destination: "Srinagar", airline: "IndiGo", flightNo: "6E-554", startingPrice: 4999, duration: "1h 30m" },
  { id: "fl-7", origin: "Mumbai", destination: "Bengaluru", airline: "SpiceJet", flightNo: "SG-331", startingPrice: 3499, duration: "1h 35m" },
  { id: "fl-8", origin: "Delhi", destination: "Leh", airline: "Air India", flightNo: "AI-445", startingPrice: 6999, duration: "1h 20m" }
];

// SECONDARY INTERNATIONAL DESTINATIONS (INR PRICING)
const INTERNATIONAL_DESTINATIONS = [
  { id: "intl-dubai", name: "Dubai", country: "UAE", priceStarting: 35000, duration: "5 Days", image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800&q=80", shortDesc: "Desert luxury, Burj Khalifa views, and world-class shopping." },
  { id: "intl-bali", name: "Bali", country: "Indonesia", priceStarting: 32000, duration: "6 Days", image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80", shortDesc: "Tropical beaches, rice terraces, and volcanic temples." },
  { id: "intl-paris", name: "Paris", country: "France", priceStarting: 75000, duration: "6 Days", image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80", shortDesc: "Eiffel Tower elegance, Louvre museum, and romantic cafes." },
  { id: "intl-swiss", name: "Switzerland", country: "Switzerland", priceStarting: 95000, duration: "7 Days", image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80", shortDesc: "Alpine glaciers, scenic trains, and pristine Swiss lakes." },
  { id: "intl-london", name: "London", country: "UK", priceStarting: 80000, duration: "6 Days", image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80", shortDesc: "Big Ben, Thames cruises, and historic royal palaces." },
  { id: "intl-singapore", name: "Singapore", country: "Singapore", priceStarting: 38000, duration: "5 Days", image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=800&q=80", shortDesc: "Gardens by the Bay, Marina Bay Sands, and island fun." },
  { id: "intl-thailand", name: "Thailand", country: "Thailand", priceStarting: 22000, duration: "5 Days", image: "https://images.unsplash.com/photo-1506665531195-3566af2b4dfa?auto=format&fit=crop&w=800&q=80", shortDesc: "Bangkok street food, Phuket islands, and golden temples." }
];

// SAMPLE INITIAL REVIEWS
const INITIAL_REVIEWS = [
  {
    id: "rev-1",
    userName: "Rahul Sharma",
    userCity: "Pune, Maharashtra",
    destination: "Goa",
    rating: 5,
    date: "2026-08-14",
    comment: "Booked the 4-day Goa Beach Escape package for ₹9,999. Incredible value for money! Everything managed seamlessly by TravelEase."
  },
  {
    id: "rev-2",
    userName: "Priya Patel",
    userCity: "Ahmedabad, Gujarat",
    destination: "Udaipur",
    rating: 5,
    date: "2026-09-02",
    comment: "Udaipur was a magical experience. The hotel recommendations in INR were completely accurate to our trip budget!"
  },
  {
    id: "rev-3",
    userName: "Amit Verma",
    userCity: "Bengaluru, Karnataka",
    destination: "Leh-Ladakh",
    rating: 5,
    date: "2026-09-18",
    comment: "The Trip Budget Calculator helped us plan our 7-day Ladakh bike trip perfectly down to the rupee. Highly recommended!"
  }
];

// PHOTO GALLERY ITEMS
const GALLERY_ITEMS = [
  { title: "Baga Sunset Beach", category: "Beach", location: "Goa", image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80" },
  { title: "Hawa Mahal Facade", category: "Heritage", location: "Jaipur", image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=800&q=80" },
  { title: "Alleppey Houseboat Canals", category: "Honeymoon", location: "Kerala", image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=800&q=80" },
  { title: "Solang Valley Snow Slopes", category: "Mountains", location: "Manali", image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80" },
  { title: "Dal Lake Shikaras", category: "Honeymoon", location: "Srinagar", image: "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=800&q=80" },
  { title: "Pangong Lake Azure Waters", category: "Adventure", location: "Ladakh", image: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=800&q=80" },
  { title: "Taj Mahal Sunrise", category: "Heritage", location: "Agra", image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80" },
  { title: "Ganga Aarti Evening", category: "Spiritual", location: "Varanasi", image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80" },
  { title: "Radhanagar Turquoise Bay", category: "Beach", location: "Andaman", image: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?auto=format&fit=crop&w=800&q=80" }
];
